version: '3.8'

services:
  backend:
    image: bmascat/ebara-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
      - "11434:11434"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OLLAMA_BASE_URL=http://host.docker.internal:11434

  frontend:
    image: bmascat/ebara-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend 
    environment:
      - BACKEND_URL=http://backend:8000